import type {
  QastackPlugin,
  Route,
  Model,
  Component,
  DatabaseSchema,
  UserStory,
  TestResult,
} from '@qastack/core';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { scanAppRoutes } from './scanners/routes.js';
import { scanPrismaSchema } from './scanners/prisma.js';
import { scanComponents } from './scanners/components.js';

const nextjsPlugin: QastackPlugin = {
  name: 'nextjs',

  detect(projectRoot: string): boolean {
    const packagePath = join(projectRoot, 'package.json');
    if (!existsSync(packagePath)) return false;
    try {
      const content = readFileSync(packagePath, 'utf-8');
      const pkg = JSON.parse(content) as Record<
        string,
        Record<string, unknown>
      >;
      const deps = pkg['dependencies'] ?? {};
      const devDeps = pkg['devDependencies'] ?? {};
      return 'next' in deps || 'next' in devDeps;
    } catch {
      return false;
    }
  },

  async scanRoutes(projectRoot: string): Promise<Route[]> {
    return scanAppRoutes(projectRoot);
  },

  async scanModels(projectRoot: string): Promise<Model[]> {
    return scanPrismaSchema(projectRoot);
  },

  async scanComponents(projectRoot: string): Promise<Component[]> {
    return scanComponents(projectRoot);
  },

  async scanSchema(projectRoot: string): Promise<DatabaseSchema> {
    // Convert Prisma models to DatabaseSchema format
    const models = scanPrismaSchema(projectRoot);
    return {
      tables: models.map((m) => ({
        name: m.table ?? m.name.charAt(0).toLowerCase() + m.name.slice(1) + 's',
        fields: m.fields,
      })),
    };
  },

  testRunner(): string {
    return 'playwright';
  },

  testTemplate(story: UserStory): string {
    const moduleSlug = story.module.toLowerCase().replace(/\s+/g, '-');

    return `// Generated by qastack from ${story.id}
// Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

import { test, expect } from '@playwright/test';

test.describe('${story.module} @${story.module}', () => {
  test('${story.id}: ${story.action} @${story.module} @${story.tier} @e2e', async ({ page }) => {
    // Next.js route -- adjust path as needed
    await page.goto('/${moduleSlug}', { waitUntil: 'domcontentloaded' });

    // TODO: [HUMAN] Verify page loaded
    // await expect(page.getByRole('heading', { name: /.../ })).toBeVisible();

    // TODO: [HUMAN] Implement test for: ${story.action}
    // Expected: ${story.expectedResult}

    // TODO: [HUMAN] Add assertions
  });
});
`;
  },

  testDir(): string {
    return 'tests/e2e';
  },

  resultFormat(): string {
    return 'playwright-json';
  },

  parseResults(_reportPath: string): TestResult[] {
    // Delegate to @qastack/collector's Playwright parser when available
    return [];
  },
};

export default nextjsPlugin;

// Re-export scanners for direct use
export { scanAppRoutes } from './scanners/routes.js';
export { scanPrismaSchema, parsePrismaSchema } from './scanners/prisma.js';
export { scanComponents } from './scanners/components.js';
