/**
 * `qastack init` — interactive project initialization.
 *
 * 1. Asks project name, AI provider, API key, DB driver
 * 2. Auto-detects framework via plugin-loader
 * 3. Generates qastack.config.js
 * 4. Runs migrations (creates SQLite DB)
 * 5. Prints success summary
 */

import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { input, select, password } from '@inquirer/prompts';
import { detectFramework, createDatabase } from '@qastack/core';
import chalk from 'chalk';
import ora from 'ora';
import { success, info, warn, withErrorHandler } from '../helpers.js';

export async function initCommand(): Promise<void> {
  await withErrorHandler(async () => {
    const cwd = process.cwd();

    console.log(
      chalk.bold('\n  qastack init\n') +
        chalk.dim('  Initialize qastack in your project\n'),
    );

    // Check if already initialized
    const configPath = resolve(cwd, 'qastack.config.js');
    if (existsSync(configPath)) {
      warn('qastack.config.js already exists. Re-running will overwrite it.');
    }

    // 1. Project name (default: directory name)
    const dirName = cwd.split(/[/\\]/).pop() ?? 'my-project';
    const projectName = await input({
      message: 'Project name:',
      default: dirName,
    });

    // 2. AI provider
    const aiProvider = await select({
      message: 'AI provider:',
      choices: [
        { value: 'anthropic', name: 'Anthropic (Claude)' },
        { value: 'openai', name: 'OpenAI (GPT)' },
      ],
    });

    // 3. AI API key (masked)
    const aiApiKey = await password({
      message: `${aiProvider === 'anthropic' ? 'ANTHROPIC_API_KEY' : 'OPENAI_API_KEY'}:`,
    });

    // 4. DB driver
    const dbDriver = await select({
      message: 'Database:',
      choices: [
        { value: 'sqlite', name: 'SQLite (recommended — zero setup)' },
        { value: 'mysql', name: 'MySQL' },
      ],
    });

    // 5. Auto-detect framework
    const spinner = ora('Detecting framework...').start();
    const framework = await detectFramework(cwd);
    spinner.succeed(`Detected framework: ${chalk.bold(framework)}`);

    // 6. Determine model default
    const model =
      aiProvider === 'anthropic' ? 'claude-sonnet-4-6' : 'gpt-4o';

    // 7. Generate config file
    const envKeyName =
      aiProvider === 'anthropic'
        ? 'ANTHROPIC_API_KEY'
        : 'OPENAI_API_KEY';

    const configContent = `// qastack.config.js — generated by \`qastack init\`
/** @type {import('@qastack/core').QastackConfig} */
export default {
  project: '${projectName}',
  ai: {
    provider: '${aiProvider}',
    model: '${model}',
    apiKey: process.env.${envKeyName} || '',
  },
  db: {
    driver: '${dbDriver}',
    ${dbDriver === 'sqlite' ? "path: './qastack.db'," : "host: 'localhost',\n    port: 3306,\n    user: 'root',\n    password: '',\n    database: 'qastack',"}
  },
  test: {
    runner: '${framework === 'laravel' ? 'pest' : 'playwright'}',
    dir: '${framework === 'laravel' ? 'tests' : 'tests/e2e'}',
    resultPath: '${framework === 'laravel' ? 'test-results.xml' : 'playwright-report/results.json'}',
    resultFormat: '${framework === 'laravel' ? 'junit-xml' : 'playwright-json'}',
  },
  discovery: {
    framework: '${framework}',
  },
  methodology: {
    tiers: ['smoke', 'regression', 'uat'],
    rootCauseCategories: ['infra', 'timeout', 'data-issue', 'ui-bug', 'assertion', 'flaky', 'unknown'],
    thresholds: {
      passRate: { warning: 80, critical: 70 },
      flakyRate: { warning: 5 },
      regressionCount: { critical: 10 },
      staleFailureRuns: { warning: 10 },
    },
  },
  dashboard: {
    port: 3847,
    auth: { user: 'admin', pass: 'qastack' },
  },
  plugins: [],
};
`;

    writeFileSync(configPath, configContent, 'utf-8');
    info(`Created ${chalk.bold('qastack.config.js')}`);

    // 8. Write .env hint if API key was provided
    if (aiApiKey) {
      const envPath = resolve(cwd, '.env');
      const envLine = `${envKeyName}=${aiApiKey}\n`;

      if (existsSync(envPath)) {
        const { appendFileSync } = await import('node:fs');
        appendFileSync(envPath, envLine);
        info(`Appended ${envKeyName} to .env`);
      } else {
        writeFileSync(envPath, envLine, 'utf-8');
        info(`Created .env with ${envKeyName}`);
      }
    }

    // 9. Run migrations (create DB)
    if (dbDriver === 'sqlite') {
      const migrateSpinner = ora('Running database migrations...').start();
      const db = await createDatabase({
        driver: 'sqlite',
        path: './qastack.db',
      });
      await db.migrate();
      await db.close();
      migrateSpinner.succeed('Database ready');
    }

    // 10. Summary
    success('qastack initialized!');
    console.log(chalk.dim('  Next steps:'));
    console.log(`    ${chalk.cyan('qastack discover')}   — scan codebase, generate user stories`);
    console.log(`    ${chalk.cyan('qastack generate')}   — create test skeletons`);
    console.log(`    ${chalk.cyan('qastack collect')}    — ingest test results`);
    console.log(`    ${chalk.cyan('qastack dashboard')} — launch monitoring UI`);
    console.log();
  });
}
