import type {
  QastackPlugin,
  Route,
  Model,
  Component,
  DatabaseSchema,
  UserStory,
  TestResult,
} from '@qastack/core';

const genericPlugin: QastackPlugin = {
  name: 'generic',

  detect(_projectRoot: string): boolean {
    // Always matches as the fallback plugin
    return true;
  },

  async scanRoutes(_projectRoot: string): Promise<Route[]> {
    // Generic plugin cannot infer routes — return empty
    // Future: parse existing test files for page.goto() patterns
    return [];
  },

  async scanModels(_projectRoot: string): Promise<Model[]> {
    // No model scanning for generic — return empty
    return [];
  },

  async scanComponents(_projectRoot: string): Promise<Component[]> {
    // Generic plugin cannot infer component structure — return empty
    // Future: scan for React/Vue/Svelte files in common directories
    return [];
  },

  async scanSchema(_projectRoot: string): Promise<DatabaseSchema> {
    // Generic plugin cannot infer schema — return empty
    // Future: check for prisma/schema.prisma, migrations/, etc.
    return { tables: [] };
  },

  testRunner(): string {
    return 'playwright';
  },

  testTemplate(story: UserStory): string {
    return `// Generated by qastack from ${story.id}
// Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

import { test, expect } from '@playwright/test';

test.describe('${story.module} @${story.module}', () => {
  test('${story.id}: ${story.action} @${story.module} @${story.tier} @e2e', async ({ page }) => {
    // TODO: [HUMAN] Set the correct URL
    await page.goto('/', { waitUntil: 'domcontentloaded' });

    // TODO: [HUMAN] Verify page loaded
    // await expect(page.getByRole('heading', { name: /.../ })).toBeVisible();

    // TODO: [HUMAN] Implement test for: ${story.action}
    // Expected: ${story.expectedResult}
  });
});
`;
  },

  testDir(): string {
    return 'tests/e2e';
  },

  resultFormat(): string {
    return 'playwright-json';
  },

  parseResults(_reportPath: string): TestResult[] {
    // Delegate to @qastack/collector's Playwright parser when available
    return [];
  },
};

export default genericPlugin;
