import { describe, it, expect } from 'vitest';
import { generatePlaywrightTest } from '../templates/playwright.js';
import type { UserStory } from '@qastack/core';

function makeStory(overrides: Partial<UserStory> = {}): UserStory {
  return {
    id: 'US-001',
    module: 'users',
    persona: 'admin',
    action: 'view user list',
    expectedResult: 'Table of users is shown',
    confidence: 'high',
    tier: 'smoke',
    source: 'discovery',
    ...overrides,
  };
}

describe('generatePlaywrightTest', () => {
  it('generates valid Playwright syntax (import, test.describe, test)', () => {
    const code = generatePlaywrightTest(makeStory());

    expect(code).toContain("import { test, expect } from '@playwright/test';");
    expect(code).toContain('test.describe(');
    expect(code).toContain('test(');
    expect(code).toContain('async ({ page })');
  });

  it('includes story ID, module, and tier tags', () => {
    const code = generatePlaywrightTest(makeStory());

    expect(code).toContain('US-001');
    expect(code).toContain('@users');
    expect(code).toContain('@smoke');
    expect(code).toContain('@e2e');
  });

  it('includes route path in goto()', () => {
    const code = generatePlaywrightTest(makeStory(), '/admin/users');

    expect(code).toContain("page.goto('/admin/users'");
  });

  it('uses "/" when no route path provided', () => {
    const code = generatePlaywrightTest(makeStory());

    expect(code).toContain("page.goto('/'");
  });

  it('contains TODO: [HUMAN] markers', () => {
    const code = generatePlaywrightTest(makeStory());

    expect(code).toContain('TODO: [HUMAN]');
    // Should have markers for expected result and action
    expect(code).toContain('TODO: [HUMAN] Table of users is shown');
    expect(code).toContain('TODO: [HUMAN] Add assertions for: view user list');
  });

  it('includes NEEDS_REVIEW status in comment', () => {
    const code = generatePlaywrightTest(makeStory());

    expect(code).toContain('Status: NEEDS_REVIEW');
  });

  it('includes module and tier in header comment', () => {
    const code = generatePlaywrightTest(makeStory({ module: 'invoices', tier: 'regression' }));

    expect(code).toContain('Module: invoices');
    expect(code).toContain('Tier: regression');
  });

  it('handles special characters in story action', () => {
    const story = makeStory({
      action: 'view "special" items & filter (by status)',
    });
    const code = generatePlaywrightTest(story);

    // Should not throw and should contain the action
    expect(code).toContain('view "special" items & filter (by status)');
  });

  it('generates correct describe title with capitalized module', () => {
    const code = generatePlaywrightTest(makeStory({ module: 'invoices' }));

    expect(code).toContain("test.describe('Invoices");
  });

  it('generates test title with story action as title case', () => {
    const code = generatePlaywrightTest(makeStory({ action: 'create new invoice' }));

    expect(code).toContain('Create New Invoice');
  });

  it('includes generated-by comment with story ID', () => {
    const code = generatePlaywrightTest(makeStory({ id: 'US-042' }));

    expect(code).toContain('Generated by qastack from US-042');
  });

  it('uses persona in test name', () => {
    const code = generatePlaywrightTest(makeStory({ persona: 'tutor' }));

    expect(code).toContain('tutor can view user list');
  });

  it('escapes regex characters in module name for heading assertion', () => {
    const story = makeStory({ module: 'tasks+items' });
    const code = generatePlaywrightTest(story);

    // The '+' should be escaped in the regex
    expect(code).toContain('Tasks\\+items');
  });
});
