import type { UserStory } from '@qastack/core';
import { capitalize, storyActionToTitle } from '../helpers.js';

export function generatePestTest(
  story: UserStory,
  routePath?: string,
): string {
  const url = routePath ?? '/';
  return `<?php
// Generated by qastack from ${story.id}
// Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

describe('${capitalize(story.module)} — ${storyActionToTitle(story.action)}', function () {
    it('${story.id}: ${story.persona} can ${story.action}', function () {
        // TODO: [HUMAN] Setup test data

        \\$response = \\$this->get('${url}');

        \\$response->assertStatus(200);
        // TODO: [HUMAN] Assert: ${story.expectedResult}
    })->group('${story.tier}');
});
`;
}
