import type { UserStory } from '@qastack/core';
import { capitalize, storyActionToTitle, escapeRegex } from '../helpers.js';

export function generatePlaywrightTest(
  story: UserStory,
  routePath?: string,
): string {
  const url = routePath ?? '/';
  return `// Generated by qastack from ${story.id}
// Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

import { test, expect } from '@playwright/test';

test.describe('${capitalize(story.module)} — ${storyActionToTitle(story.action)} @${story.module}', () => {
  test('${story.id}: ${story.persona} can ${story.action} @${story.module} @${story.tier} @e2e', async ({ page }) => {
    // 1. Navigate
    await page.goto('${url}', { waitUntil: 'domcontentloaded' });

    // 2. Verify page loaded
    await expect(page.getByRole('heading', { name: /${escapeRegex(capitalize(story.module))}/i })).toBeVisible();

    // 3. Verify expected result
    // TODO: [HUMAN] ${story.expectedResult}

    // 4. Verify key interactions
    // TODO: [HUMAN] Add assertions for: ${story.action}
  });
});
`;
}
