import type { UserStory } from '@qastack/core';
import { capitalize, storyActionToTitle } from '../helpers.js';

export function generatePytestTest(
  story: UserStory,
  _routePath?: string,
): string {
  const className = capitalize(story.module);
  const methodSuffix = story.action
    .replace(/\s+/g, '_')
    .toLowerCase()
    .slice(0, 50);
  const methodId = story.id.toLowerCase().replace(/-/g, '_');

  return `# Generated by qastack from ${story.id}
# Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

import pytest

class Test${className}:
    """${storyActionToTitle(story.action)}"""

    @pytest.mark.${story.tier}
    def test_${methodId}_${methodSuffix}(self, client):
        """${story.id}: ${story.persona} can ${story.action}"""
        # TODO: [HUMAN] Setup test data

        # TODO: [HUMAN] Execute action: ${story.action}

        # TODO: [HUMAN] Assert: ${story.expectedResult}
        pass
`;
}
