import type { UserStory } from '@qastack/core';
import { capitalize, storyActionToTitle } from '../helpers.js';

export function generateRspecTest(
  story: UserStory,
  _routePath?: string,
): string {
  return `# Generated by qastack from ${story.id}
# Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

RSpec.describe '${capitalize(story.module)} — ${storyActionToTitle(story.action)}', type: :feature do
  it '${story.id}: ${story.persona} can ${story.action}' do
    # TODO: [HUMAN] Setup test data

    # TODO: [HUMAN] Execute action: ${story.action}

    # TODO: [HUMAN] Assert: ${story.expectedResult}
  end
end
`;
}
