import { describe, it, expect } from 'vitest';
import type { UserStory } from '@qastack/core';
import genericPlugin from '../index.js';

const sampleStory: UserStory = {
  id: 'US-001',
  module: 'auth',
  persona: 'admin',
  action: 'login with valid credentials',
  expectedResult: 'User is redirected to dashboard',
  confidence: 'high',
  tier: 'smoke',
  source: 'manual',
};

describe('generic plugin', () => {
  it('detect() always returns true', () => {
    expect(genericPlugin.detect('/any/path')).toBe(true);
    expect(genericPlugin.detect('')).toBe(true);
  });

  it('testRunner() returns "playwright"', () => {
    expect(genericPlugin.testRunner()).toBe('playwright');
  });

  it('testDir() returns "tests/e2e"', () => {
    expect(genericPlugin.testDir()).toBe('tests/e2e');
  });

  it('resultFormat() returns "playwright-json"', () => {
    expect(genericPlugin.resultFormat()).toBe('playwright-json');
  });

  it('scanRoutes() returns empty array', async () => {
    const routes = await genericPlugin.scanRoutes('/any/path');
    expect(routes).toEqual([]);
  });

  it('scanModels() returns empty array', async () => {
    const models = await genericPlugin.scanModels('/any/path');
    expect(models).toEqual([]);
  });

  it('scanComponents() returns empty array', async () => {
    const components = await genericPlugin.scanComponents('/any/path');
    expect(components).toEqual([]);
  });

  it('scanSchema() returns empty tables', async () => {
    const schema = await genericPlugin.scanSchema('/any/path');
    expect(schema).toEqual({ tables: [] });
  });

  it('parseResults() returns empty array', () => {
    const results = genericPlugin.parseResults('/any/report.json');
    expect(results).toEqual([]);
  });

  it('testTemplate() generates valid Playwright test with story data', () => {
    const template = genericPlugin.testTemplate(sampleStory);

    // Contains Playwright imports
    expect(template).toContain("import { test, expect } from '@playwright/test'");

    // Contains story ID and module
    expect(template).toContain('US-001');
    expect(template).toContain('auth');

    // Contains story action and expected result
    expect(template).toContain('login with valid credentials');
    expect(template).toContain('User is redirected to dashboard');

    // Contains tier tag
    expect(template).toContain('@smoke');

    // Contains e2e tag
    expect(template).toContain('@e2e');
  });

  it('testTemplate() includes TODO markers', () => {
    const template = genericPlugin.testTemplate(sampleStory);

    expect(template).toContain('TODO: [HUMAN]');
    // Should have multiple TODO markers
    const todoCount = (template.match(/TODO: \[HUMAN\]/g) ?? []).length;
    expect(todoCount).toBeGreaterThanOrEqual(3);
  });

  it('testTemplate() includes Generated-by header', () => {
    const template = genericPlugin.testTemplate(sampleStory);
    expect(template).toContain('Generated by qastack from US-001');
  });

  it('testTemplate() includes NEEDS_REVIEW status', () => {
    const template = genericPlugin.testTemplate(sampleStory);
    expect(template).toContain('NEEDS_REVIEW');
  });

  it('name is "generic"', () => {
    expect(genericPlugin.name).toBe('generic');
  });
});
