import type {
  QastackPlugin,
  Route,
  Model,
  Component,
  DatabaseSchema,
  UserStory,
  TestResult,
} from '@qastack/core';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { scanRoutes } from './scanners/routes.js';
import { scanModels } from './scanners/models.js';
import { scanMigrations } from './scanners/migrations.js';

const laravelPlugin: QastackPlugin = {
  name: 'laravel',

  detect(projectRoot: string): boolean {
    const composerPath = join(projectRoot, 'composer.json');
    if (!existsSync(composerPath)) return false;
    try {
      const content = readFileSync(composerPath, 'utf-8');
      const composer = JSON.parse(content) as Record<
        string,
        Record<string, unknown>
      >;
      const require = composer['require'] ?? {};
      return 'laravel/framework' in require;
    } catch {
      return false;
    }
  },

  async scanRoutes(projectRoot: string): Promise<Route[]> {
    return scanRoutes(projectRoot);
  },

  async scanModels(projectRoot: string): Promise<Model[]> {
    return scanModels(projectRoot);
  },

  async scanComponents(projectRoot: string): Promise<Component[]> {
    // Scan resources/js/Pages/*.tsx for Inertia projects
    const pagesDir = join(projectRoot, 'resources', 'js', 'Pages');
    if (!existsSync(pagesDir)) return [];

    // Future: recursively scan for .tsx/.vue files
    // For now, return empty — component scanning is a lower priority
    return [];
  },

  async scanSchema(projectRoot: string): Promise<DatabaseSchema> {
    return scanMigrations(projectRoot);
  },

  testRunner(): string {
    return 'playwright';
  },

  testTemplate(story: UserStory): string {
    // Determine the likely URL from the module name
    const moduleSlug = story.module.toLowerCase().replace(/\s+/g, '-');

    return `// Generated by qastack from ${story.id}
// Module: ${story.module} | Tier: ${story.tier} | Status: NEEDS_REVIEW

import { test, expect } from '@playwright/test';

test.describe('${story.module} @${story.module}', () => {
  test('${story.id}: ${story.action} @${story.module} @${story.tier} @e2e', async ({ page }) => {
    // Laravel route — adjust path as needed
    await page.goto('/${moduleSlug}', { waitUntil: 'domcontentloaded' });

    // TODO: [HUMAN] Verify page loaded
    // await expect(page.getByRole('heading', { name: /.../ })).toBeVisible();

    // TODO: [HUMAN] Implement test for: ${story.action}
    // Expected: ${story.expectedResult}

    // TODO: [HUMAN] Add assertions
  });
});
`;
  },

  testDir(): string {
    return 'tests/e2e';
  },

  resultFormat(): string {
    return 'playwright-json';
  },

  parseResults(_reportPath: string): TestResult[] {
    // Delegate to @qastack/collector's Playwright parser when available
    return [];
  },
};

export default laravelPlugin;

// Re-export scanners for direct use
export { scanRoutes } from './scanners/routes.js';
export { scanModels } from './scanners/models.js';
export { scanMigrations } from './scanners/migrations.js';
export { parseRouteFile } from './scanners/routes.js';
export { parseModelFile, inferTableName } from './scanners/models.js';
export { parseMigrationFile } from './scanners/migrations.js';
